src/Entity/Media.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MediaRepository")
 */
class Media
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="filename", type="string", length=255)
     */
    private $fileName;

    /**
     * @var File
     *
     * @Assert\File()
     * @Assert\NotBlank(message="Veuiller Uploader un fichier.")
     */
    private $file;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    public function setFileName(string $fileName): self
    {
        $this->fileName = $fileName;

        return $this;
    }

    public function getFile(): ?File
    {
        return $this->file;
    }

    public function setFile(?File $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }


    public function getWebPath() {
        return 'uploads/'.$this->fileName;
    }
}

src/Controller/BackOffice/BackOfficeController.php
<?php

namespace App\Controller\BackOffice;

use App\Entity\Category;
use App\Entity\Command;
use App\Entity\Media;
use App\Entity\Product;
use App\Entity\ProductMedia;
use App\Form\CategoryType;
use App\Form\ProductType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\User;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BackOfficeController extends Controller
{
    /**
     * @Route("/back_office/", name="back_office_home")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction(Request $request)
    {
        return $this->render('back_office/index.html.twig');
    }
}

src/Controller/BackOffice/BlogController.php
<?php

namespace App\Controller\BackOffice;

use App\Entity\Post;
use App\Entity\PostTag;
use App\Entity\PostCategory;
use App\Form\PostCategoryType;
use App\Form\PostTagType;
use App\Form\PostType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends Controller
{
    /**
     * @Route("/back_office/blog/category", name="back_office_blog_category")
     * @param Request $request
     * @return Response
     */
    public function indexCategoryAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $categories = $em->getRepository('App:PostCategory')->findAll();

        return $this->render('back_office/blog/category/index.html.twig', array(
            'categories' => $categories
        ));
    }

    /**
     * @Route("/back_office/blog/add/category", name="back_office_add_blog_category")
     * @param Request $request
     * @return Response
     */
    public function addCategoryAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $category = new PostCategory();
        $form = $this->createForm(PostCategoryType::class, $category);

        $form->handleRequest($request);
        if ($form->isSubmitted())
        {
            if ($category->getMedia())
            {
                $fileName = $this->get('file_saver')->saveFile(
                    $category->getMedia()->getFile(), 'media_directory'
                );
                $category->getMedia()->setFileName($fileName);
            }

            $em->persist($category);
            $em->flush();
            $this->addFlash('notification', 'Catégorie ajoutée avec succès!');
            return  $this->redirectToRoute('back_office_blog_category');
        }

        return $this->render('back_office/blog/category/new.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @Route("/back_office/blog/category/{id}/edit", name="back_office_edit_blog_category")
     * @param Request $request
     * @param PostCategory $category
     * @return Response
     */
    public function editCategoryAction(Request $request, PostCategory $category)
    {
        $em = $this->getDoctrine()->getManager();

        if ($category->getMedia())
            $category->getMedia()->setFile(
                new File($this->getParameter('media_directory').'/'. $category->getMedia()->getFileName())
            );

        $form = $this->createForm(PostCategoryType::class, $category);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            if ($category->getMedia() !== null && $category->getMedia()->getFile() !== null)
            {
                $fileName = $this->get('file_saver')->saveFile(
                    $category->getMedia()->getFile(), 'media_directory'
                );
                $category->getMedia()->setFileName($fileName);
            }

            $em->persist($category);
            $em->flush();
            $this->addFlash('notification', 'Catégorie modifiée avec succès!');
            return $this->redirectToRoute('back_office_blog_category');
        }


        return $this->render('back_office/blog/category/edit.html.twig', [
            'category' => $category,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/back_office/blog/category/{id}/delete", name="back_office_delete_blog_category")
     * @param PostCategory $category
     * @return Response
     */
    public function deleteCategoryAction(PostCategory $category)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($category);
        $em->flush();
        $this->addFlash('notification', 'Catégorie supprimée avec succès!');
        return $this->redirectToRoute('back_office_blog_category');
    }



    /**
     * @Route("/back_office/blog/post", name="back_office_blog_post")
     * @param Request $request
     * @return Response
     */
    public function indexPostAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $posts = $em->getRepository('App:Post')->findAll();

        return $this->render('back_office/blog/post/index.html.twig', array(
            'posts' => $posts
        ));
    }

    /**
     * @Route("/back_office/blog/show/post/{id}", name="back_office_show_blog_post")
     * @param Post $post
     * @return Response
     */
    public function showPostAction(Post $post)
    {
        return $this->render('back_office/blog/post/show.html.twig', array(
            'post' => $post
        ));
    }

    /**
     * @Route("/back_office/blog/add/post", name="back_office_add_blog_post")
     * @param Request $request
     * @return Response
     */
    public function addPostAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);

        $form->handleRequest($request);
        if ($form->isSubmitted())
        {
            if ($post->getMedia())
            {
                $fileName = $this->get('file_saver')->saveFile(
                    $post->getMedia()->getFile(), 'media_directory'
                );
                $post->getMedia()->setFileName($fileName);
            }

            $em->persist($post);
            $em->flush();
            $this->addFlash('notification', 'Article ajouté avec succès!');
            return  $this->redirectToRoute('back_office_blog_post');
        }

        return $this->render('back_office/blog/post/new.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @Route("/back_office/blog/post/{id}/edit", name="back_office_edit_blog_post")
     * @param Request $request
     * @param Post $post
     * @return Response
     */
    public function editPostAction(Request $request, Post $post)
    {
        $em = $this->getDoctrine()->getManager();

        if ($post->getMedia())
            $post->getMedia()->setFile(
                new File($this->getParameter('media_directory').'/'. $post->getMedia()->getFileName())
            );

        $form = $this->createForm(PostType::class, $post);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            if ($post->getMedia()->getFile() !== null)
            {
                $fileName = $this->get('file_saver')->saveFile(
                    $post->getMedia()->getFile(), 'media_directory'
                );
                $post->getMedia()->setFileName($fileName);
            }

            $em->persist($post);
            $em->flush();
            $this->addFlash('notification', 'Article modifié avec succès!');
            return $this->redirectToRoute('back_office_blog_post');
        }


        return $this->render('back_office/blog/post/edit.html.twig', [
            'post' => $post,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/back_office/blog/post/{id}/delete", name="back_office_delete_blog_post")
     * @param Post $post
     * @return Response
     */
    public function deletePostAction(Post $post)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($post);
        $em->flush();
        $this->addFlash('notification', 'Article supprimé avec succès!');
        return $this->redirectToRoute('back_office_blog_post');
    }



    /**
     * @Route("/back_office/blog/tag", name="back_office_blog_tag")
     * @param Request $request
     * @return Response
     */
    public function indexTagAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $tags = $em->getRepository('App:PostTag')->findAll();

        return $this->render('back_office/blog/tag/index.html.twig', array(
            'tags' => $tags
        ));
    }

    /**
     * @Route("/back_office/blog/add/tag", name="back_office_add_blog_tag")
     * @param Request $request
     * @return Response
     */
    public function addTagAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $tag = new PostTag();
        $form = $this->createForm(PostTagType::class, $tag);

        $form->handleRequest($request);
        if ($form->isSubmitted())
        {
            $em->persist($tag);
            $em->flush();
            $this->addFlash('notification', 'Etiquette ajouté avec succès!');
            return  $this->redirectToRoute('back_office_blog_tag');
        }

        return $this->render('back_office/blog/tag/new.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @Route("/back_office/blog/tag/{id}/edit", name="back_office_edit_blog_tag")
     * @param Request $request
     * @param PostTag $tag
     * @return Response
     */
    public function editTagAction(Request $request, PostTag $tag)
    {
        $em = $this->getDoctrine()->getManager();

        $form = $this->createForm(PostTagType::class, $tag);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $em->persist($tag);
            $em->flush();
            $this->addFlash('notification', 'Etiquette modifié avec succès!');
            return $this->redirectToRoute('back_office_blog_tag');
        }


        return $this->render('back_office/blog/tag/edit.html.twig', [
            'tag' => $tag,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/back_office/blog/tag/{id}/delete", name="back_office_delete_blog_tag")
     * @param PostTag $tag
     * @return Response
     */
    public function deleteTagAction(PostTag $tag)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($tag);

src/Controller/BackOffice/CategoryController.php
<?php

namespace App\Controller\BackOffice;

use App\Entity\Category;
use App\Form\CategoryType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CategoryController extends Controller
{
    /**
     * @Route("/back_office/category", name="back_office_category")
     * @param Request $request
     * @return Response
     */
    public function indexCategoryAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $categories = $em->getRepository('App:Category')->findAll();

        return $this->render('back_office/category/index.html.twig', array(
            'categories' => $categories
        ));
    }

    /**
     * @Route("/back_office/category/add", name="back_office_add_category")
     * @param Request $request
     * @return Response
     */
    public function addCategoryAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $category = new Category();
        $form = $this->createForm(CategoryType::class, $category);

        $form->handleRequest($request);
        if ($form->isSubmitted())
        {
            if ($category->getMedia())
            {
                $fileName = $this->get('file_saver')->saveFile(
                    $category->getMedia()->getFile(), 'media_directory'
                );
                $category->getMedia()->setFileName($fileName);
            }

            $em->persist($category);
            $em->flush();
            $this->addFlash('notification', 'Catégorie ajoutée avec succès!');
            return  $this->redirectToRoute('back_office_category');
        }

        return $this->render('back_office/category/new.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @Route("/back_office/category/{id}/edit", name="back_office_edit_category")
     * @param Request $request
     * @param Category $category
     * @return Response
     */
    public function editCategoryAction(Request $request, Category $category)
    {
        $em = $this->getDoctrine()->getManager();

        if ($category->getMedia())
            $category->getMedia()->setFile(
                new File($this->getParameter('media_directory').'/'. $category->getMedia()->getFileName())
            );

        $form = $this->createForm(CategoryType::class, $category);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            if ($category->getMedia() !== null && $category->getMedia()->getFile() !== null)
            {
                $fileName = $this->get('file_saver')->saveFile(
                    $category->getMedia()->getFile(), 'media_directory'
                );
                $category->getMedia()->setFileName($fileName);
            }

            $em->persist($category);
            $em->flush();
            $this->addFlash('notification', 'Catégorie modifiée avec succès!');
            return $this->redirectToRoute('back_office_category');
        }


        return $this->render('back_office/category/edit.html.twig', [
            'category' => $category,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/back_office/category/{id}/delete", name="back_office_delete_category")
     * @param Category $category
     * @return Response
     */
    public function deleteCategoryAction(Category $category)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($category);
        $em->flush();
        $this->addFlash('notification', 'Catégorie supprimée avec succès!');
        return $this->redirectToRoute('back_office_category');
    }
}

templates/back_office/product/edit.html.twig
{% extends 'back_office/layout.html.twig' %}

{% block title %} Modifier un produit {% endblock %}

{% block breadcrumb %} Modifier un produit {% endblock %}

{% block container %}
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-lg-8 col-8">
                <!-- Basic Forms -->
                <div class="box">
                    <div class="box-header with-border">
                        <h4 class="box-title">Modifier un produit</h4>
                        <ul class="box-controls pull-right">
                            {#<li><a class="box-btn-close" href="#"></a></li>#}
                            <li><a class="box-btn-slide" href="#"></a></li>
                            {#<li><a class="box-btn-fullscreen" href="#"></a></li>#}
                        </ul>
                    </div>
                    <!-- /.box-header -->
                    {{ form_start(form) }}
                    <div class="box-body">
                        <h4 class="mt-0 mb-20"></h4>
                        <div class="form-group">
                            <label>{{ form_label(form.category) }}</label>
                            {{ form_widget(form.category, {attr: { class: 'form-control' }}) }}
                        </div>
                        <div class="form-group">
                            <label>{{ form_label(form.name) }}</label>
                            {{ form_widget(form.name, {attr: { class: 'form-control', placeholder: 'Libéllé' }}) }}
                        </div>
                        <div class="form-group">
                            <label>{{ form_label(form.price) }}</label>
                            {{ form_widget(form.price, {attr: { class: 'form-control', placeholder: 'Prix' }}) }}
                        </div>
                        <div class="form-group">
                            <label>{{ form_label(form.stock) }}</label>
                            {{ form_widget(form.stock, {attr: { class: 'form-control', placeholder: 'Stock' }}) }}
                        </div>
                        <div class="form-group">
                            <label>{{ form_label(form.description) }}</label>
                            {{ form_widget(form.description, {attr: { class: 'form-control', placeholder: 'Description' }}) }}
                        </div>
                        <div class="demo-checkbox">
                            {{ form_widget(form.featured) }}
                            {{ form_label(form.featured) }}
                        </div>
                        <div class="form-group">
                            <label>Image de mise en avant:</label>
                            {{ form_widget(form.media.file, {attr: { class: 'form-control'}}) }}
                        </div>
                        <hr>
                        <div class="form-group">
                            <label style="width: 100%;">Autres images:
                                <a style="float: right;" class=" btn btn-sm btn-rounded btn-outline-info" id="add_file">
                                    Ajouter une autre image
                                </a>
                            </label>
                            {{ form_widget(form.medias, {attr: { class: 'form-control'}}) }}
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <input type="submit" class="btn btn-success" value="Enregistrer">
                    </div>
                    {{ form_rest(form) }}
                    {{ form_end(form) }}
                </div>
                <!-- /.box -->
            </div>
            <div class="col-4">

                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Images</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body border-dark border-bottom">
                        <div class="flexbox align-items-center">
                            <div class="flexbox">
                                <label class="toggler toggler-yellow">
                                    <input type="checkbox" checked="">
                                    <i class="fa fa-star"></i>
                                </label>
                                <h4 class="ml-10 mb-0"><a href="#">Image de mis en garde</a></h4>
                            </div>
                            <div class="dropdown">
                                <a data-toggle="dropdown" href="#" aria-expanded="false"><i class="ion-android-more-vertical"></i></a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    {#<a class="dropdown-item" href="#"><i class="fa fa-fw fa-user"></i> Profile</a>#}
                                    {#<a class="dropdown-item" href="#"><i class="fa fa-fw fa-comments"></i> Messages</a>#}
                                    {#<a class="dropdown-item" href="#"><i class="fa fa-fw fa-phone"></i> Call</a>#}
                                    {#<div class="dropdown-divider"></div>#}
                                    <a class="dropdown-item" href="#"><i class="fa fa-fw fa-remove"></i> Supprimer</a>
                                </div>
                            </div>
                        </div>
                        <div class="text-center pt-15">
                            <a style="width: 100%;" href="#" class="pull-left">
                                <img class="avatar avatar-xxl rounded" src="{{ asset(product.media.webPath) }}" alt="">
                            </a>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    {% for pm in productMedias %}
                        <div class="m-t-5 box-body">
                            <div class="flexbox align-items-center">
                                <div class="flexbox">
                                    <h4 class="ml-10 mb-0"><a href="#">Autres images</a></h4>
                                </div>
                                <div class="dropdown">
                                    <a data-toggle="dropdown" href="#" aria-expanded="false"><i class="ion-android-more-vertical"></i></a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        {#<a class="dropdown-item" href="#"><i class="fa fa-fw fa-user"></i> Profile</a>#}
                                        {#<a class="dropdown-item" href="#"><i class="fa fa-fw fa-comments"></i> Messages</a>#}
                                        {#<a class="dropdown-item" href="#"><i class="fa fa-fw fa-phone"></i> Call</a>#}
                                        {#<div class="dropdown-divider"></div>#}
                                        <a class="dropdown-item" href="#"><i class="fa fa-fw fa-remove"></i> Supprimer</a>
                                    </div>
                                </div>
                            </div>
                            <div class="text-center pt-15">
                                <a style="width: 100%;" href="#" class="pull-left">
                                    <img class="avatar avatar-xxl rounded" src="{{ asset(pm.media.webPath) }}" alt="">
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <!-- /.box -->
            </div>
        </div>
    </section>
    <!-- /.content -->
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $(document).ready(function () {
            // On récupère la balise <div> en question qui contient l'attribut « data-prototype » qui nous intéresse.
            var $container = $('div#product_medias');

            // On définit un compteur unique pour nommer les champs qu'on va ajouter dynamiquement
            var index = $container.find('input').length;

            // On ajoute un nouveau champ à chaque clic sur le lien d'ajout.
            $('#add_file').click(function (e) {
                addFile($container);
                e.preventDefault(); // évite qu'un # apparaisse dans l'URL
                return false;
            });

            // On ajoute un premier champ automatiquement s'il n'en existe pas déjà un (cas d'une nouvelle annonce par exemple).
            if (index === 0) {
                addFile($container);
            } else {
                // S'il existe déjà des catégories, on ajoute un lien de suppression pour chacune d'entre elles
                $container.children('div').each(function (i) {
                    addDeleteLink($(this));
                    // Et aussi un libelle correct
                    $($(this).children('label')[0]).text('Image n°' + (i+1))
                });
            }

            // La fonction qui ajoute un formulaire CategoryType
            function addFile($container) {
                // Dans le contenu de l'attribut « data-prototype », on remplace :
                // - le texte "__name__label__" qu'il contient par le label du champ
                // - le texte "__name__" qu'il contient par le numéro du champ
                var template = $container.attr('data-prototype')
                    .replace(/__name__label__/g, 'Image n°' + (index + 1))
                    .replace(/__name__/g, index)
                    .replace('<div><label', '<div class="row"><label')
                ;
                // On crée un objet jquery qui contient ce template
                var $prototype = $(template);

                // On ajoute au prototype un lien pour pouvoir supprimer la catégorie
                addDeleteLink($prototype);

                // On ajoute le prototype modifié à la fin de la balise <div>
                $container.append($prototype);

                var idMess = 'product_medias' + index + '_filename';

                // CKEDITOR.replace(idMess);

                // Enfin, on incrémente le compteur pour que le prochain ajout se fasse avec un autre numéro
                index++;
            }

            // La fonction qui ajoute un lien de suppression d'une catégorie
            function addDeleteLink($prototype) {
                // Création du lien
                var $deleteLink = $('<button type="button" href="#" class="btn btn-sm btn-outline-danger m-t-5 m-b-10 col-2"><i class="fa fa-trash"></i></button>');

                // Ajout du lien
                $prototype.append($deleteLink);

                // Ajout du listener sur le clic du lien pour effectivement supprimer la catégorie
                $deleteLink.click(function (e) {
                    $prototype.remove();

                    e.preventDefault(); // évite qu'un # apparaisse dans l'URL
                    return false;
                });
            }
        });
    </script>

    {% if product.media %}
        <script>
            $('#product_media_file').removeAttr('required')
        </script>
    {% endif %}
{% endblock %}